### ISSUE TITLE
Prijedlog poveznice na pravu sliku u README.md

### ISSUE THREAD

**Issue by sbravar** [SolderedElectronics/Soldered-BQ27441-Battery-Fuel-Gauge-Arduino-Library#1]
https://github.com/SolderedElectronics/Soldered-BQ27441-Battery-Fuel-Gauge-Arduino-Library/blob/f5450a9b36032e1dc59e23a28dd38021ae06bd35/README.md?plain=1#L7C34-L7C103

umjesto:

https://upload.wikimedia.org/wikipedia/commons/8/8f/Example_image.svg

čini mi se da bi moglo biti:

https://github.com/SolderedElectronics/Fuel-gauge-BQ27441-breakout-hardware-design/blob/main/OUTPUTS/V1.0.0/333065.jpg?raw=true

**Comment by rsoric** [comment]
Hello, and thank you for your feedback. We are currently working on automating this process. Soon, all repositories will be updated with the real content. Cheers!
